modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
updateJSONURL="https://api.modrinth.com/updates/WBvnqHfV/forge_updates.json"
displayURL="https://astonishing-chord-210.notion.site/194f058bb4ac80c2979fdfe22fb8010e"
logoFile="assets/natures_spirit/icon.png"
authors = "${mod_authors}"

description = '''${mod_description}'''
[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "terrablender"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"