modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "All Rights Reserved"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "Nature's Spirit"
updateJSONURL="https://api.modrinth.com/updates/WBvnqHfV/forge_updates.json"
displayURL="https://astonishing-chord-210.notion.site/194f058bb4ac80c2979fdfe22fb8010e"
logoFile="assets/natures_spirit/icon.png"
authors = "Team Hibiscus"


[[mixins]]
config="natures_spirit.mixins.json"

description = '''A mod to expand Minecraft's nature!'''
[[dependencies."${mod_id}"]]
modId = "neoforge"
mandatory = true
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "terrablender"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"